import React, { createContext, useContext, useState } from 'react';

type Language = 'am' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  am: {
    'nav.home': 'ዋና ገጽ',
    'nav.about': 'ስለ እኛ',
    'nav.services': 'አገልግሎቶች',
    'nav.dashboard': 'ዳሽቦርድ',
    'nav.admin': 'አድሚን',
    'nav.login': 'ግባ',
    'nav.signup': 'ተመዝገብ',
    'nav.logout': 'ውጣ',
    'common.search': 'ፈልግ...',
    'common.cancel': 'ሰርዝ',
    'common.save': 'መዝግብ',
    'common.exit': 'ውጣ',
    'common.back': 'ተመለስ',
    'common.next': 'ቀጥል',
    'common.or': 'ወይም',
    'common.payout': 'ደራሽ',
    'common.etb': 'ብር',
    'common.appName': 'መሊቅ እቁብ',
    
    // User Menu
    'menu.user.overview': 'አጠቃላይ እይታ',
    'menu.user.members': 'የቡድን አባላት',
    'menu.user.payments': 'የእኔ መዋጮዎች',
    'menu.user.draws': 'የእጣ ውጤቶች',
    'menu.user.chat': 'ውይይት',
    'menu.user.rules': 'ህጎች እና ደንቦች',
    'menu.user.guarantors': 'የዋስትና መረጃ',
    'menu.user.notifications': 'ማሳወቂያዎች',
    'menu.user.leaderboard': 'ግንባር ቀደም አባላት',
    'menu.user.support': 'እርዳታ ጠይቅ',
    'menu.user.settings': 'ማስተካከያ',
    'menu.user.faq': 'ጥያቄዎች',
    'menu.user.penalties': 'ቅጣቶች',
    'menu.user.documents': 'ሰነዶች',
    'menu.user.profile': 'ፕሮፋይል',
    'menu.user.market': 'የገበያ ማዕከል',

    // Admin Menu
    'menu.admin.analytics': 'ትንታኔ',
    'menu.admin.pending': 'ማረጋገጫ የሚጠብቁ (KYC)',
    'menu.admin.guarantors': 'የዋስ መረጃዎች',
    'menu.admin.all_members': 'ሁሉም አባላት',
    'menu.admin.groups': 'የምድቦች ስብስብ',
    'menu.admin.draws': 'የእጣ ውጤቶች',
    'menu.admin.payments': 'መዋጮዎች',
    'menu.admin.payouts': 'ክፍያዎች (Payout)',
    'menu.admin.penalties': 'ቅጣቶች አስተዳደር',
    'menu.admin.chat': 'ውይይት ማስተዳደር',
    'menu.admin.support': 'የእርዳታ ጥያቄዎች',
    'menu.admin.reports': 'ሪፖርቶች',
    'menu.admin.audit': 'የስርዓት ኦዲት',
    'menu.admin.notifications': 'ማሳወቂያ ላክ',
    'menu.admin.market': 'የገበያ ማዕከል',
    'menu.admin.settings': 'የስርዓት አቀማመጥ',
    'menu.admin.admins': 'የአድሚን ቡድን',

    'dashboard.welcome': 'እንኳን ደህና መጡ',
    'dashboard.total_payout': 'ጠቅላላ ደራሽ',
    'dashboard.contribution': 'መዋጮ',
    'dashboard.active_slots': 'ንቁ እጣዎች',
    'dashboard.community': 'ማህበረሰብ',
    'dashboard.history': 'ታሪክ',
    'dashboard.identity': 'ማንነት',
    'dashboard.chat': 'ውይይት',
    'dashboard.rules': 'ህጎች',
    'dashboard.main_box': 'ዋና ሳጥን',
    'dashboard.send_payment': 'ክፍያ ላክ',
    'dashboard.system_state': 'የሲስተም ሁኔታ',
    'dashboard.live': 'ቀጥታ',
    'admin.panel': 'የአስተዳደር ፔናል',
    'admin.verification': 'ማረጋገጫ',
    'admin.users': 'አባላት',
    'admin.pools': 'ቡድኖች',
    'admin.audit': 'ኦዲት',
    'admin.staff': 'ሰራተኞች',
    'admin.approve': 'አጽድቅ',
    'admin.reject': 'ውድቅ',
    'admin.details': 'ዝርዝር',
    'admin.verification_pending': 'ማረጋገጫ የሚጠብቁ',
    'landing.welcome': 'እንኳን ወደ መሊቅ እቁብ በደህና መጡ',
    'landing.hero.title': 'የእቁብ አስተዳደርን',
    'landing.hero.title_modern': 'በዘመናዊ',
    'landing.hero.title_way': 'መንገድ',
    'landing.hero.subtitle': 'መሊቅ እቁብ የቆየውን ባህል ከዘመናዊ ቴክኖሎጂ ጋር በማቀናጀት ግልጽነትን፣ ደህንነትን እና ምቾትን ያመጣል።',
    'landing.hero.cta': 'አሁኑኑ ይመዝገቡ',
    'landing.hero.login': 'ግባ',
    'landing.join_cta': 'ወደ እቁብ ይቀላቀሉ',
    'landing.video_cta': 'የአሰራር ቪዲዮ',
    'landing.global_members': 'አባላት',
    'landing.life_title': 'የእቁብ ህይወትዎን በዘመናዊ መንገድ ይምሩ',
    'landing.life_desc': 'ከወረቀት እና ከባህላዊ ስህተቶች የፀዳ፣ በቴክኖሎጂ የታገዘ ግልጽ እና ደህንነቱ የተጠበቀ የእቁብ አገልግሎት።',
    'landing.trust_points.1': '100% ግልጽነት',
    'landing.trust_points.2': 'ፈጣን ክፍያ',
    'landing.trust_points.3': 'የታመነ ዋስትና',
    'landing.about.title': 'እቁብ ምንድን ነው?',
    'landing.about.desc': 'እቁብ የኢትዮጵያውያን የቆየ የቁጠባ እና የብድር ባህል ነው። አባላት በየጊዜው የተወሰነ ገንዘብ በማዋጣት፣ በተራ ወይም በዕጣ ለሚያስፈልገው አባል በመስጠት እርስ በርስ ይረዳዳሉ። መሊቅ እቁብ ይህንን ስርዓት በቴክኖሎጂ በማዘመን ይበልጥ ግልጽ እና አስተማማኝ ያደርገዋል።',
    'feature.admin.title': 'ቀላል አስተዳደር',
    'feature.admin.desc': 'የእቁብ ቡድኖችን እና አባላትን በቀላሉ ይቆጣጠሩ።',
    'feature.security.title': 'አስተማማኝ ክፍያ',
    'feature.security.desc': 'ክፍያዎችን በዘመናዊ መንገድ ይከታተሉ እና ያረጋግጡ።',
    'feature.transparency.title': 'ግልጽነት',
    'feature.transparency.desc': 'የእቁብ እንቅስቃሴዎችን በግልጽ በዝርዝር ይከታተሉ።',
    'feature.rewards.title': 'የአባላት ሽልማት',
    'feature.rewards.desc': 'ለአባላት ልዩ ሽልማቶችን እና ማበረታቻዎችን ያቅርቡ።',
    'feature.reports.title': 'ሪፖርቶች',
    'feature.reports.desc': 'የእቁብ እንቅስቃሴዎችን በዝርዝር ሪፖርት ይከታተሉ።',
    'feature.fast.title': 'ፈጣን አገልግሎት',
    'feature.fast.desc': 'የእቁብ ሂደቶችን በፍጥነት ይተግብሩ።',
    'btn.save': 'አስቀምጥ',
    'btn.cancel': 'ሰርዝ',
    'signin': 'ግባ',
    'signup': 'ተመዝገብ',
    'phone': 'ስልክ ቁጥር',
    'password': 'የይለፍ ቃል',
    'full_name': 'ሙሉ ስም',
    'country': 'ሀገር',
    'region': 'ክልል',
    'zone': 'ዞን',
    'woreda': 'ወረዳ',
    'kebele': 'ቀበሌ',
    'google_access': 'በጎግል ይግቡ',
    'no_account': 'አካውንት የሎትም?',
    'join_now': 'አሁኑኑ ይቀላቀሉ',
    'signup.personal': 'ግላዊ መረጃ',
    'signup.birthplace': 'የትውልድ ቦታ',
    'signup.address': 'አድራጃ/አድራሻ',
    'signup.ekub_group': 'እቁብና ቡድን',
    'signup.kyc_photo': 'KYC & ፎቶ',
    'signup.confirmation': 'ማረጋገጫ',
    'signup.identity_verification': 'የማንነት ማረጋገጫ',
    'signup.age': 'እድሜ',
    'birth_country': 'የትውልድ ሀገር',
    'birth_region': 'የትውልድ ክልል',
    'birth_zone': 'የትውልድ ዞን',
    'birth_woreda': 'የትውልድ ወረዳ',
    'birth_kebele': 'የትውልድ ቀበሌ',
    'birth_date': 'የትውልድ ቀን',
    'common.step': 'ደረጃ',
    'common.finish': 'ምዝገባ ጨርስ',
    'signup.frequency': 'የእቁብ አይነት',
    'signup.members': 'የአባላት ብዛት',
    'signup.contribution': 'የመዋጮ መጠን',
    'signup.slots': 'እጣ ብዛት',
    'signup.custom_amount': 'የራስዎን መጠን ያስገቡ',
    'signup.national_id': 'የናሽናል አይዲ ቁጥር',
    'signup.face_scan': 'የፊት ስካን',
    'signup.id_front': 'የመታወቂያ ፊት',
    'signup.id_back': 'የመታወቂያ ጀርባ',
    'signup.terms': 'በህግ እና ደንቡ እስማማለሁ',
    'signup.success_title': 'ምዝገባው ተሳክቷል!',
    'signup.member_code': 'የአባልነት ኮድ',
    'signup.group_label': 'ምድብ',
    'signup.registered_success_msg': 'ምዝገባው በተሳካ ሁኔታ ተጠናቋል!',
    'signup.custom.option': 'የራስዎን...',
    'signup.slot_unit': 'እጣ',
    'signup.spots_open': 'ቦታ ክፍት ነው',
    'signup.registered_count': 'ተመዝግቧል',
    'signup.remaining_count': 'ቀርቷል',
    'signup.take_photo': 'ፎቶ አንሳ',
    'signup.photo_uploaded': 'ፎቶ ተጭኗል (Uploaded)',
    'signup.upload_face_photo': 'የፊት ፎቶዎን እዚህ ይጫኑ',
    'signup.face_photo_security': 'ለደህንነት ሲባል የፊት ፎቶ ያስፈልጋል',
    'signup.registration_summary': 'የምዝገባ ማጠቃለያ',
    'signup.new_pool': 'አዲስ ቡድን',
    'signup.view_terms': 'ህግ እና ደንቦችን ዝርዝር ይመልከቱ',
    'signup.finish_registration_note': 'መረጃዎን ካረጋገጡ በኋላ ከታች ያለውን "ምዝገባ ጨርስ" ቁልፍ በመጫን ምዝገባዎን ያጠናቅቁ።',
    'signup.daily': 'በየቀኑ ተሰብስቦ በ10 ቀን እጣ ይወጣል',
    'signup.weekly': 'በየሳምንቱ',
    'signup.monthly': 'በየወሩ',
    'signup.fivedays': 'በየቀን ተሰብስቦ በ5 ቀን እጣ ይወጣል',
    'signup.tendays': 'በየቀኑ ተሰብስቦ በ10 ቀን እጣ ይወጣል',
    'signup.daily_desc': 'በየቀኑ ተሰብስቦ በ10 ቀን እጣ ይወጣል',
    'signup.fivedays_desc': 'በየቀን ተሰብስቦ በ5 ቀን እጣ ይወጣል',
    'signup.tendays_desc': 'በየቀኑ ተሰብስቦ በ10 ቀን እጣ ይወጣል',
    'signup.weekly_desc': 'በየሳምንቱ መዋጮ ይሰበሰባል፣ በዛው ቀን እጣ ይወጣል።',
    'signup.monthly_desc': 'በየወሩ መዋጮ ይሰበሰባል፣ በዛው ቀን እጣ ይወጣል።',
    'signup.cycle_note': 'ይህ የእቁብ አይነት ለአንድ ዙር {days} ቀናት ይቆያል',
    'signup.payout_calc': 'የሚደርስዎ ብር = ({amount} ብር * {duration}) * {members} አባላት',
    'signup.choose_group': 'ምድብ ይምረጡ',
    'signup.error.full_name': 'እባክዎ ሙሉ ስምዎን ያስገቡ',
    'signup.error.phone': 'እባክዎ ስልክ ቁጥርዎን ያስገቡ',
    'signup.error.password': 'እባክዎ የይለፍ ቃል ያስገቡ',
    'signup.error.birth_country': 'እባክዎ የትውልድ ሀገር ያስገቡ',
    'signup.error.birth_region': 'እባክዎ የትውልድ ክልል ያስገቡ',
    'signup.error.birth_zone': 'እባክዎ የትውልድ ዞን ያስገቡ',
    'signup.error.registration_failed': 'የምዝገባ ስህተት ተከስቷል',
    'signup.error.phone_already_used': 'ይህ ስልክ ቁጥር ቀድሞ ጥቅም ላይ ውሏል',
    'signup.alert.camera_denied': 'ካሜራ መጠቀም አልተቻለም። እባክዎ ፈቃድ ይስጡ።',
    'signup.error.birth_woreda': 'እባክዎ የትውልድ ወረዳ ያስገቡ',
    'signup.error.birth_kebele': 'እባክዎ የትውልድ ቀበሌ ያስገቡ',
    'signup.error.birth_date': 'እባክዎ የትውልድ ቀን በትክክል ያስገቡ',
    'signup.error.age_limit': 'ለመመዝገብ ቢያንስ 18 አመት መሆን አለብዎት',
    'signup.error.address_country': 'እባክዎ የመኖሪያ ሀገር ያስገቡ',
    'signup.error.address_region': 'እባክዎ የመኖሪያ ክልል ያስገቡ',
    'signup.error.address_zone': 'እባክዎ የመኖሪያ ዞን ያስገቡ',
    'signup.error.address_woreda': 'እባክዎ የመኖሪያ ወረዳ ያስገቡ',
    'signup.error.address_kebele': 'እባክዎ የመኖሪያ ቀበሌ ያስገቡ',
    'signup.error.id_front': 'እባክዎ የመታወቂያ ፊት ፎቶ ያስገቡ',
    'signup.error.id_back': 'እባክዎ የመታወቂያ ጀርባ ፎቶ ያስገቡ',
    'signup.error.face_scan': 'እባክዎ የፊት ፎቶ ያስገቡ',
    'signup.error.national_id': 'እባክዎ ብሔራዊ መታወቂያ ቁጥር ያስገቡ',
    'signup.error.terms': 'እባክዎ በህግ እና ደንቡ መስማማትዎን ያረጋግጡ',
    'signup.error.already_registered': 'ይህ ስልክ ቁጥር ቀድሞ ተመዝግቧል። እባክዎ ይግቡ ወይም ሌላ ቁጥር ይጠቀሙ።',
    'signup.error.frequency': 'እባክዎ የእቁብ አይነት ይምረጡ',
    'signup.error.member_limit': 'እባክዎ የአባላት ብዛት ይምረጡ',
    'signup.error.amount': 'እባክዎ የመዋጮ መጠን ያስገቡ',
    'signup.error.id_front_attach': 'እባክዎ የመታወቂያ ፊት ፎቶ ያያይዙ',
    'signup.error.id_back_attach': 'እባክዎ የመታወቂያ ጀርባ ፎቶ ያያይዙ',
    'signup.error.face_scan_perform': 'እባክዎ የፊት ስካን ያድርጉ',
    'signup.error.terms_agree': 'እባክዎ መጀመሪያ በህግ እና ደንቡ መስማማትዎን ያረጋግጡ',
    'common.year': 'አመት',
    'common.year_unit': 'አመት',
    'common.people': 'አባላት',
    'common.day': 'ቀን',
    'calendar.gc': 'በፈረንጅ',
    'calendar.ec': 'በኢትዮጵያ',
    'calendar.year': 'ዓመት',
    'calendar.month': 'ወር',
    'calendar.day': 'ቀን',
    'calendar.gregorian': 'Gregorian',
    'calendar.ethiopian': 'Ethiopian',
    'signup.age_label': 'እድሜ',
    'signup.payout_label': 'የሚጠበቅ ድምር ዕጣ',
    'btn.continue': 'ይቀጥሉ',
    'signup.birthplace.region': 'የትውልድ ክልል',
    'signup.birthplace.zone': 'የትውልድ ዞን',
    'signup.birthplace.woreda': 'የትውልድ ወረዳ',
    'signup.birthplace.kebele': 'የትውልድ ቀበሌ',
    'signup.address.region': 'ክልል',
    'signup.address.zone': 'ዞን',
    'signup.address.woreda': 'ወረዳ',
    'signup.address.kebele': 'ቀበሌ',
    'signup.terms_desc': 'የእቁብ ህግ እና ደንቦች፡\n1. አባላት በመዋጮ ወቅት መዘግየት የለባቸውም። በወቅቱ ያልከፈለ አባል በህጉ መሰረት ይቀጣል።\n2. እጣ የደረሰው አባል እጣውን ከመውሰዱ በፊት ሦስት (3) ዋሶችን ማቅረብ ይኖርበታል።\n3. ዋሶች የፋይዳ መታወቂያ (Fayda ID) እና የንግድ ፈቃድ (Business License) ማቅረብ ግዴታ ይኖርባቸዋል።\n4. እጣ የደረሰው አባል በአካል ቀርቦ የስም መሙያ ቀን እና "ደርሶኛል" የሚል ማረጋገጫ መፈረም ይኖርበታል።\n5. ዋሶችም ስማቸውን፣ ስራቸውን እና አድራሻቸውን በመጥቀስ በዋስትና ሰነዱ ላይ መፈረም ይኖርባቸዋል።\n6. ማንኛውም አባል መዋጮውን ሳያጠናቅቅ ከእቁቡ መውጣት አይችልም።\n7. አድሚኑ የእቁቡን ደህንነት የመጠበቅ እና ደንብ የጣሱ አባላትን የማገድ ሙሉ ስልጣን አለው።',
    'dashboard.loading': 'መረጃ በመጫን ላይ...',
    'dashboard.won_title': 'እንኳን ደስ አለዎት!',
    'dashboard.won_subtitle': 'የዚህ ዙር እጣ አሸናፊ ነዎት',
    'dashboard.guarantor_form': 'የዋሶች መረጃ (Guarantor Form)',
    'dashboard.guarantor_label': 'የዋስ መለያ',
    'dashboard.guarantor_name': 'የዋስ ሙሉ ስም',
    'dashboard.guarantor_job': 'የዋስ ስራ / አድራሻ',
    'dashboard.guarantor_confirm': 'በአካል የምፈርም መሆኑን አረጋግጣለሁ',
    'dashboard.send_guarantors': 'የዋስትና መረጃዎችን ላክ',
    'dashboard.pending_title': 'ምዝገባዎ በመጠባበቅ ላይ ነው',
    'dashboard.pending_desc': 'መረጃዎ በአድሚን እየተገመገመ ነው። አንዴ ሲረጋገጥ ሙሉ አገልግሎቶችን ማግኘት ይችላሉ። እባክዎ በትዕግስት ይጠብቁ።',
    'dashboard.contribute_title': 'መዋጮ ይላኩ',
    'dashboard.contribute_desc': 'እባክዎ የሚከፍሉትን መጠን ያረጋግጡ። ክፍያው በአድሚን ከተረጋገጠ በኋላ ወደ ሂሳብዎ ይጨመራል።',
    'dashboard.receipt_label': 'የክፍያ ማረጋገጫ (Receipt)',
    'dashboard.receipt_upload': 'ፎቶ ይምረጡ / ያንሱ',
    'dashboard.submit_payment': 'ክፍያ ፈጽም',
    'dashboard.payment_sent_success': 'መዋጮዎ ተልኳል! በአድሚን ሲረጋገጥ በዝርዝሩ ውስጥ ይታያል።',
    'dashboard.payment_sent_error': 'መዋጮ መላክ አልተሳካም። እባክዎ እንደገና ይሞክሩ።',
    'dashboard.next_draw': 'ቀጣይ እጣ',
    'dashboard.draw_soon': 'በቅርቡ...',
    'dashboard.total_cycle': 'ጠቅላላ ዙር',
    'dashboard.summary': 'የምዝገባ ማጠቃለያ',
    'dashboard.rules.1.title': 'የመዋጮ ስነስርዓት',
    'dashboard.rules.1.content': 'አባላት በመዋጮ ወቅት መዘግየት የለባቸውም። በወቅቱ ያልከፈለ አባል በህጉ መሰረት ይቀጣል።',
    'dashboard.rules.2.title': 'የዋስትና ግዴታ (ለአሸናፊዎች)',
    'dashboard.rules.2.content': 'እጣ የደረሰው አባል እጣውን ከመውሰዱ በፊት ሦስት (3) ዋሶችን ማቅረብ ይኖርበታል።',
    'dashboard.rules.3.title': 'የዋሶች ማስረጃ',
    'dashboard.rules.3.content': 'ዋሶች የፋይዳ መታወቂያ (Fayda ID) እና የንግድ ፈቃድ (Business License) ማቅረብ ግዴታ ይኖርባቸዋል።',
    'dashboard.rules.4.title': 'የደርሶኛል ማረጋገጫ',
    'dashboard.rules.4.content': 'እጣ የደረሰው አባል በአካል ቀርቦ የስም መሙያ ቀን እና "ደርሶኛል" የሚል ማረጋገጫ መፈረም ይኖርበታል።',
    'dashboard.rules.5.title': 'የዋሶች ፊርማ',
    'dashboard.rules.5.content': 'ዋሶችም ስማቸውን፣ ስራቸውን እና አድራሻቸውን በመጥቀስ በዋስትና ሰነዱ ላይ መፈረም ይኖርባቸዋል።',
    'dashboard.rules.6.title': 'አጠቃላይ ድንጋጌዎች',
    'dashboard.rules.6.content': 'ማንኛውም አባል መዋጮውን ሳያጠናቅቅ ከእቁቡ መውጣት አይችልም። አድሚኑ የእቁቡን ደህንነት የመጠበቅ እና ደንብ የጣሱ አባላትን የማገድ ሙሉ ስልጣን አለው።',
    
    // Additional Admin/Common
    'admin.management': 'አመራር',
    'admin.operations': 'ክዋኔዎች',
    'admin.system': 'ሲስተም',
    'chat.voice_message': 'የድምፅ መልዕክት',
    'chat.all_members': 'ሁሉንም አባላት',
    'chat.admin': 'አድሚን',
    'chat.type_message': 'መልዕክት ይጻፉ...',
    'status.pending': 'በመጠባበቅ ላይ',
    'status.active': 'ንቁ',
    'status.rejected': 'ውድቅ የተደረገ',
    'status.verified': 'የተረጋገጠ',
    'status.verified_secure': 'የተረጋገጠ እና አስተማማኝ',
    'status.action_required': 'እርምጃ ያስፈልጋል: ኦዲት',
    'auth.exit_admin': 'ከአድሚን ውጣ',
    'auth.welcome_back': 'እንኳን ደህና መጡ!',
    'auth.user_not_found': 'በዚህ ስልክ ቁጥር የተመዘገበ ተጠቃሚ አልተገኘም',
    'auth.verification_code_sms': 'የእርስዎ ማረጋገጫ ኮድ፡ {code}',
    'auth.error_try_again': 'ስህተት ተከስቷል፣ እባክዎ እንደገና ይሞክሩ',
    'auth.invalid_code': 'ማረጋገጫ ኮዱ ስህተት ነው',
    'auth.password_min_length': 'የይለፍ ቃል ቢያንስ 6 አሃዝ መሆን አለበት',
    'auth.password_changed': 'የይለፍ ቃልዎ ተቀይሯል! አሁን መግባት ይችላሉ።',
    'auth.password_change_failed': 'የይለፍ ቃል መቀየር አልተሳካም',
    'auth.enter_phone': 'እባክዎ ስልክ ቁጥርዎን ያስገቡ',
    'auth.enter_password': 'እባክዎ የይለፍ ቃል ያስገቡ',
    'auth.incorrect_admin_password': 'የአድሚን ይለፍ ቃል ስህተት ነው',
    'auth.admin_creation_failed': 'አድሚን መፍጠር አልተሳካም: ',
    'auth.invalid_credentials': 'የመግቢያ መረጃ ስህተት ነው (ስልክ ወይም የይለፍ ቃል)',
    'auth.admin_login_issue': 'የአድሚን መግቢያ ችግር፡ እባክዎ በትክክል መፃፍዎን ያረጋግጡ።',
    'auth.google_login_failed': 'ጎግል መግቢያ አልተሳካም',
    'auth.forgot_password_title': 'የይለፍ ቃል ለመቀየር',
    'auth.enter_phone_subtitle': 'ስልክ ቁጥርዎን ያስገቡ',
    'auth.sending': 'በመላክ ላይ...',
    'auth.send_code': 'ኮድ ላክ',
    'auth.verify_code_title': 'ኮዱን ያረጋግጡ',
    'auth.verify_code_subtitle': 'ባለ 6 አሃዝ ኮድ ይሙሉ።',
    'auth.verify_button': 'አረጋግጥ',
    'auth.new_password_title': 'አዲስ የይለፍ ቃል',
    'auth.new_password_subtitle': 'አዲሱን የይለፍ ቃል ያስገቡ',
    'auth.changing_password': 'በመቀየር ላይ...',
    'auth.forgot_password': 'የይለፍ ቃል ረስተዋል?',
    'auth.login_button': 'ግባ',
    'auth.loading_login': 'በመግባት ላይ...',
    'auth.enter_phone_placeholder': 'ለምሳሌ 0912345678',
    'auth.enter_password_placeholder': 'የይለፍ ቃልዎን እዚህ ያስገቡ',
    'auth.terms_service': 'የአገልግሎት ስምምነት',
    'auth.privacy_policy': 'የግላዊነት ፖሊሲ',
    'auth.secure_gateway': 'ደህንነቱ የተጠበቀ መግቢያ',
    'auth.admin_detected': 'አድሚን ተገኝቷል',
    'auth.registration_success': 'ምዝገባዎ በተሳካ ሁኔታ ተጠናቋል',
    'auth.unique_code': 'የእርስዎ ልዩ መለያ ኮድ',
    'auth.enter_portal': 'ወደ መሊቅ እቁብ ይግቡ',
    'receipt.id': 'የደረሰኝ ቁጥር',
    'receipt.verified': 'የተረጋገጠ',
    'receipt.id_status': 'የአይዲ ሁኔታ',
    'receipt.active_license': 'ንቁ ፈቃድ',
    'receipt.legal_req': 'ከክፍያ በፊት የህግ ማረጋገጫ ያስፈልጋል',
    'receipt.download_success': 'ደረሰኝ በተሳካ ሁኔታ ወርዷል',
    'receipt.download_error': 'ደረሰኝ ማውረድ አልተሳካም',
    'payout.pending_ledger': 'የክፍያ ዝርዝር ባዶ ነው',
    'payout.no_guarantors': 'ምንም የዋስ መረጃ የለም',
    'payout.guarantor_assets': 'የዋስ መረጃዎች',
    'payout.mandatory_kyc': 'አስገዳጅ የማንነት ማረጋገጫ (3/3 ተይዟል)',
    'payout.guarantor_unit': 'የዋስ መረጃ',
    'group.start': 'ምድቡን አስጀምር',
    'group.draw': 'እጣ አውጣ',
    'group.no_members': 'ቡድኑ አባላት የሉትም',
    'group.started': 'ምድቡ ተጀምሯል!',
    'group.winner_selected': 'አሸናፊው ተመርጠዋል!',
    'common.language': 'ቋንቋ',
    'common.english': 'English',
    'common.amharic': 'አማርኛ',
    'common.units': 'እጣዎች',
    'common.unit_value': 'የእጣ ዋጋ',
    'common.total_cycle': 'ጠቅላላ ዙር',
    
    // Admin Alerts & Operations
    'admin.user_approved': 'ተጠቃሚው ጸድቋል!',
    'admin.user_approval_failed': 'ማጽደቅ አልተሳካም',
    'admin.user_rejected': 'ተጠቃሚው ውድቅ ተደርጓል',
    'admin.user_rejection_failed': 'ውድቅ ማድረግ አልተሳካም',
    'admin.user_delete_confirm': 'ይህንን ተጠቃሚ እርግጠኛ ነዎት ውድቅ ማድረግ ይፈልጋሉ?',
    'admin.user_delete_permanent_confirm': 'ይህንን ተጠቃሚ ሙሉ በሙሉ ማጥፋት ይፈልጋሉ? ይህ ድርጊት አይመለስም።',
    'admin.user_deleted': 'ተጠቃሚው ተሰርዟል',
    'admin.user_deletion_failed': 'መሰረዝ አልተሳካም',
    'admin.admin_added': 'አዲስ አስተዳዳሪ በተሳካ ሁኔታ ተጨምሯል!',
    'admin.admin_add_failed': 'አስተዳዳሪ መጨመር አልተሳካም',
    'admin.admin_permissions_updated': 'የአስተዳዳሪ ፍቃድ ተስተካክሏል!',
    'admin.admin_update_failed': 'ማስተካከል አልተሳካም',
    'admin.required_fields': 'እባክዎ ሁሉንም አስፈላጊ መረጃዎች በትክክል ይሙሉ',
    'admin.phone_already_registered': 'ይህ ስልክ ቁጥር ቀድሞ ተመዝግቧል',
    'admin.password_weak': 'የይለፍ ቃሉ በጣም ደካማ ነው',
    'admin.member_registration_success': 'አዲስ አባል በተሳካ ሁኔታ ተመዝግቧል!',
    'admin.member_registration_failed': 'አባል መመዝገብ አልተሳካም',
    'admin.user_info_updated': 'የተጠቃሚ መረጃ ተስተካክሏል!',
    'admin.user_update_failed': 'ማስተካከል አልተሳካም',
    'admin.payment_approved': 'ክፍያው ጸድቋል!',
    'admin.payment_approval_failed': 'ክፍያውን ማጽደቅ አልተሳካም',
    'admin.payment_rejected': 'ክፍያው ውድቅ ተደርጓል',
    'admin.payment_rejection_failed': 'ውድቅ ማድረግ አልተሳካም',
    'admin.notification_sent': 'ማሳወቂያ ተልኳል',
    'admin.payment_registered_success': 'ክፍያ በተሳካ ሁኔታ ተመዝግቧል!',
    'admin.payment_registration_failed': 'ክፍያ መመዝገብ አልተሳካም',
    'admin.pdf_generation_error': 'ደረሰኝ ማመንጨት አልተሳካም',
    'admin.group_started': 'ምድቡ ተጀምሯል!',
    'admin.group_start_failed': 'ምድቡን ማስጀመር አልተሳካም',
    'admin.draw_winner_confirm': 'እርግጠኛ ነዎት አሸናፊ እንዲሆኑ ይፈልጋሉ?',
    'admin.draw_winner_error': 'አሸናፊ ለመምረጥ አልተሳካም',
    'admin.winner_notification_title': 'እንኳን ደስ አለዎት!',
    'admin.winner_notification_message': 'የዚህ ዙር የእቁብ አሸናፊ ሆነዋል። እንኳን ደስ አለዎት!',
    'time.just_now': 'አሁኑኑ',
    'time.hours_ago': 'ከ {hours} ሰዓት በፊት',
    'time.days_ago': 'ከ {days} ቀን በፊት',
    'time.unknown': 'ያልታወቀ',
    
    // UI Sections & Headers
    'admin.kyc_verification_hub': 'የማረጋገጫ ማእከል',
    'admin.identity_audit_subtitle': 'የአባላትን ማንነት እና ሰነድ ያረጋግጡ',
    'admin.search_records_placeholder': 'አባልን በስም ወይም በስልክ ፈልግ...',
    'admin.regional_intake_dist': 'የአካባቢ ስርጭት',
    'admin.pending_audits_empty': 'ምንም የሚጠባበቁ አባላት የሉም',
    'admin.kyc_requirements_met': 'ሁሉም የማረጋገጫ መስፈርቶች ተሟልተዋል',
    'admin.security_clearance': 'የደህንነት ምርመራ',
    'admin.audit_assets': 'ሰነዶችን ኦዲት አድርግ',
    'admin.verify_identity': 'አባልነትን አጽድቅ',
    'admin.master_directory_intelligence': 'የአባላት ማውጫ',
    'admin.verified_directory': 'የተረጋገጡ አባላት',
    'admin.active_status': 'ንቁ ሁኔታ',
    'admin.regional_clusters': 'የክልል ስብስቦች',
    'admin.system_health': 'የሲስተም ጤንነት',
    'admin.group_ecosystem': 'የቡድኖች አስተዳደር',
    'admin.group_monitor_subtitle': 'የቡድኖች እንቅስቃሴ እና አባላት ክትትል',
    'admin.total_groups': 'ጠቅላላ ቡድኖች',
    'admin.live': 'ቀጥታ / የሚንቀሳቀሱ',
    'admin.total_winners': 'ጠቅላላ አሸናፊዎች',
    'admin.total_value': 'ጠቅላላ ፈንድ',
    'admin.legal_guarantors': 'የዋስ መረጃዎች',
    'admin.trust_verification_subtitle': 'የዋስትና ሰነዶች ኦዲት ማእከል',
    'admin.under_review': 'በግምገማ ላይ',
    'admin.legal_compliance_policy': 'የህግ ተገዢነት ፖሊሲ',
    'admin.identity_verification': 'የማንነት ማረጋገጫ',
    'admin.reviewing_profile': 'የአባል ፕሮፋይል ኦዲት',
    'admin.liveness_check': 'የቀጥታ ስካን',
    'admin.document_verification': 'የሰነድ ማረጋገጫ',
    'admin.reject_request': 'ጥያቄውን ውድቅ አድርግ',
    'admin.confirm_approve_member': 'አባልነትን አጽድቅ',
    'admin.revenue_insight': 'የክፍያ ክንውን',
    'admin.recent_logs': 'የቅርብ ጊዜ እንቅስቃሴዎች',
    'admin.new_signups': 'አዲስ ተመዝጋቢዎች',
    'admin.last_6_months': 'ባለፉት 6 ወራት',
    'admin.user_growth': 'የአባላት እድገት',
    'admin.add_new_member': 'አዲስ አባል ጨምር',
    'admin.members_directory': 'የአባላት ማውጫ',
    'admin.groups_directory_desc': 'የቡድኖች እንቅስቃሴ እና አባላት ክትትል',
    'admin.draws_desc': 'የዕጣ ሂደቱን መቆጣጠር እና ማስተዳደር',
    'admin.guarantors_desc': 'የዋስ መረጃዎችን እና የዋስትና ሰነዶችን ማስተዳደር',
    'admin.admins_desc': 'የአድሚኖችን መብት ፣ ምዝገባና ቁጥጥር ያስተዳድሩ',
    'admin.professional_profile': 'የስራ ፕሮፋይል',
    'admin.broadcast': 'አጠቃላይ መልእክት',
    'admin.broadcast_subtitle': 'ለሁሉም አባላት የሚላክ',
    'admin.group_channel_subtitle': 'የቡድን ውይይት',
    'admin.direct_message_subtitle': 'የግል መልእክት',
    'admin.no_messages_yet': 'ምንም መልእክት የለም',
    'admin.type_message_placeholder': 'መልእክት ይጻፉ...',
    'admin.edit_message_placeholder': 'መልእክቱን ያስተካክሉ...',
    'admin.group_chats': 'የቡድን ውይይቶች',
    'admin.private_chats': 'የግል ውይይቶች',
    'admin.paid': 'ተከፍሏል',
    'admin.addis_ababa': 'አዲስ አበባ',
    'admin.oromia': 'ኦሮሚያ',
    'admin.amhara': 'አማራ',
    'admin.tigray': 'ትግራይ',
    'admin.sidama': 'ሲዳማ',
    'admin.somali': 'ሶማሊ',
    'admin.all_regions': 'ሁሉም ክልሎች',
    'admin.recorded': 'ተመዝግቧል',
    'admin.phone_registered': 'ይህ ስልክ ቁጥር ቀድሞ ተመዝግቧል። እባክዎ ሌላ ቁጥር ይጠቀሙ።',
    'admin.weak_password': 'የይለፍ ቃሉ በጣም ደካማ ነው። ቢያንስ 6 አሃዝ ይሁን።',
    'admin.user_registered_success': 'አዲስ አባል በተሳካ ሁኔታ ተመዝግቧል። አሁን አባሉ በስልክ ቁጥሩ እና በመረጡት የይለፍ ቃል ሎጊን ማድረግ ይችላል!',
    'admin.admin_label': 'አድሚን',
    'admin.photo_id': 'ፎቶ መታወቂያ',
    'admin.full_bio': 'ሙሉ መረጃ',
    'admin.documents': 'ሰነዶች',
    'admin.confidence': 'እርግጠኝነት',
    'admin.user_updated': 'የተጠቃሚ መረጃ ተስተካክሏል!',
    'admin.payment_approve_failed': 'ክፍያውን ማጽደቅ አልተሳካም',
    'admin.payment_reject_confirm': 'ይህንን ክፍያ እርግጠኛ ነዎት ውድቅ ማድረግ ይፈልጋሉ?',
    'admin.payment_reject_failed': 'ውድቅ ማድረግ አልተሳካም',
    'admin.language_label': 'ባህል/ቋንቋ',
    'admin.view_grid': 'ግሪድ',
    'admin.view_list': 'ዝርዝር',
    'admin.audit_required': 'ኦዲት ያስፈልጋል',
    'admin.identity_staking': 'የማንነት ማረጋገጫ (3/3 ተመዝግቧል)',
    'admin.pay': 'ክፈል',
    'admin.no_pending_payments': 'ምንም በመጠባበቅ ላይ ያለ ክፍያ የለም',
    'admin.no_payment_history': 'ምንም የክፍያ ታሪክ የለም',
    'admin.pending_upload': 'ሰነድ አልተጫነም',
    'admin.send_notification': 'ማሳወቂያ ይላኩ',
    'admin.subject': 'ርዕስ',
    'admin.message': 'መልእክት',
    'admin.send': 'ላክ',
    'admin.winner_selected_msg': 'አሸናፊው {name} ተመርጠዋል!',
    'admin.draw_failed': 'አሸናፊ ለመምረጥ አልተሳካም',
    'admin.no_members_in_group': 'ቡድኑ አባላት የሉትም',
    'admin.winner_confirm_msg': 'እርግጠኛ ነዎት {name} አሸናፊ እንዲሆኑ ይፈልጋሉ?',
    'admin.receipt': 'ደረሰኝ',
    'admin.super_access': 'ሱፐር አክሰስ',
    'admin.administrator': 'አስተዳዳሪ',
    'admin.profession': 'ሙያ',
    'admin.bank_name': 'የባንክ ስም',
    'admin.bank_account': 'የሂሳብ ቁጥር',
    'admin.security_note_title': 'ደህንነትዎ የተጠበቀ ነው',
    'admin.security_note_desc': 'እዚህ የሚመዘገቡ አባላት በራሳቸው ስልክ ቁጥር እና በመረጡት የይለፍ ቃል በቀጥታ መግባት ይችላሉ። የግል መረጃቸውን በሚስጥር ይጠበቃል።',
    'admin.add_member_button': 'አባሉን መዝግብ',
    'admin.stat_awaiting_audit': 'ኦዲት የሚጠባበቁ',
    'admin.stat_throughput': 'የኦዲት ፍጥነት',
    'admin.stat_confidence': 'የእርግጠኝነት መጠን',
    'admin.stat_directory_size': 'አጠቃላይ ማውጫ',
    'admin.pot_fund': 'ጠቅላላ ፈንድ',
    'admin.membership_fill': 'የአባላት ምዝገባ',
    'admin.recent_contributors': 'የቅርብ ጊዜ ተሳታፊዎች',
    'admin.no_members_yet': 'ምንም አባል አልተቀላቀለም',
    'admin.contribution_slots': 'የእጣ ብዛት',
    'admin.legal_framework': 'የህግ ማዕቀፍ',
    'admin.legal_framework_subtitle': 'የመሊቅ እቁብ የአሰራር ህግ እና ደንቦች',
    'admin.integrity_notice_title': 'የስርዓቱ ደህንነት ማሳወቂያ',
    'admin.integrity_notice_desc': 'እነዚህ የመመሪያ ህጎች በሁሉም አባላት ዘንድ ተፈፃሚነት ያላቸው እና የእቁቡን ህልውና ለማስቀጠል የተረቀቁ ናቸው። ማንኛውም አወዛጋቢ ጉዳይ ሲያጋጥም የአድሚን ውሳኔ የመጨረሻ ይሆናል።',
    'admin.registration_period': 'የምዝገባ ወቅት',
    'rules.title_1': 'የመዋጮ ስነስርዓት',
    'rules.content_1': 'አባላት በመዋጮ ወቅት መዘግየት የለባቸው። በወቅቱ ያልከፈለ አባል በህጉ መሰረት ይቀጣል።',
    'rules.title_2': 'የዋስትና ግዴታ (ለአሸናፊዎች)',
    'rules.content_2': 'እጣ የደረሰው አባል እጣውን ከመውሰዱ በፊት ሦስት (3) ዋሶችን ማቅረብ ይኖርበታል።',
    'rules.title_3': 'የዋሶች ማስረጃ',
    'rules.content_3': 'ዋሶች የፋይዳ መታወቂያ (Fayda ID) እና የንግድ ፈቃድ (Business License) ማቅረብ ግዴታ ይኖርባቸዋል።',
    'rules.title_4': 'የደርሶኛል ማረጋገጫ',
    'rules.content_4': 'እጣ የደረሰው አባል በአካል ቀርቦ የስም መሙያ ቀን እና "ደርሶኛል" የሚል ማረጋገጫ መፈረም ይኖርበታል።',
    'rules.title_5': 'የዋሶች ፊርማ',
    'rules.content_5': 'ዋሶችም ስማቸውን፣ ስራቸውን እና አድራሻቸውን በመጥቀስ በዋስትና ሰነዱ ላይ መፈረም ይኖርባቸዋል።',
    'rules.title_6': 'አጠቃላይ ድንጋጌዎች',
    'rules.content_6': 'ማንኛውም አባል መዋጮውን ሳያጠናቅቅ ከእቁቡ መውጣት አይችልም። አድሚኑ የእቁቡን ደህንነት የመጠበቅ እና ደንብ የጣሱ አባላትን የማገድ ሙሉ ስልጣን አለው።',
    'dashboard.notifications': 'ማሳወቂያዎች',
    'dashboard.recent_notifications': 'የቅርብ ጊዜ ማሳወቂያዎች',
    'dashboard.no_notifications': 'ምንም ማሳወቂያ የለም',
    'dashboard.core_support': 'ዋና ድጋፍ',
    'dashboard.support_desc': 'ስለ እቁቡ ወይም ስለ ማንኛውም የአሰራር ጥያቄ ካለዎት የድጋፍ ሰጪ ቡድናችንን በማንኛውም ጊዜ ማግኘት ይችላሉ።',
    'dashboard.contact_support': 'ድጋፍን ያግኙ',
  },
  en: {
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.dashboard': 'Dashboard',
    'nav.admin': 'Admin',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'nav.logout': 'Logout',
    'common.search': 'Search...',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.exit': 'Exit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.or': 'or',
    'common.payout': 'Payout',
    'common.etb': 'ETB',
    'common.appName': 'Meliq Equb',
    
    // User Menu
    'menu.user.overview': 'Overview',
    'menu.user.members': 'Members',
    'menu.user.payments': 'My Payments',
    'menu.user.draws': 'Draw Results',
    'menu.user.chat': 'Chat',
    'menu.user.rules': 'Rules & Terms',
    'menu.user.guarantors': 'Guarantors',
    'menu.user.notifications': 'Notifications',
    'menu.user.leaderboard': 'Leaderboard',
    'menu.user.support': 'Support',
    'menu.user.settings': 'Settings',
    'menu.user.faq': 'FAQ',
    'menu.user.penalties': 'Penalties',
    'menu.user.documents': 'Documents',
    'menu.user.profile': 'Profile',
    'menu.user.market': 'Marketplace',

    // Admin Menu
    'menu.admin.analytics': 'Analytics',
    'menu.admin.pending': 'Pending KYC',
    'menu.admin.guarantors': 'Guarantors',
    'menu.admin.all_members': 'All Members',
    'menu.admin.groups': 'Groups',
    'menu.admin.draws': 'Draws',
    'menu.admin.payments': 'Payments',
    'menu.admin.payouts': 'Payouts',
    'menu.admin.penalties': 'Penalties',
    'menu.admin.chat': 'Chat Management',
    'menu.admin.support': 'Support Tickets',
    'menu.admin.reports': 'Reports',
    'menu.admin.audit': 'System Audit',
    'menu.admin.notifications': 'Notifications',
    'menu.admin.market': 'Marketplace',
    'menu.admin.settings': 'Settings',
    'menu.admin.admins': 'Admins',

    'dashboard.welcome': 'Welcome',
    'dashboard.total_payout': 'Total Payout',
    'dashboard.contribution': 'Contribution',
    'dashboard.active_slots': 'Active Slots',
    'dashboard.community': 'Community',
    'dashboard.history': 'History',
    'dashboard.identity': 'Identity',
    'dashboard.chat': 'Chat',
    'dashboard.rules': 'Rules',
    'dashboard.main_box': 'Main Box',
    'dashboard.send_payment': 'Send Payment',
    'dashboard.system_state': 'System State',
    'dashboard.live': 'Live',
    'admin.panel': 'Admin Panel',
    'admin.verification': 'Verification',
    'admin.users': 'Users',
    'admin.pools': 'Pools',
    'admin.audit': 'Audit',
    'admin.staff': 'Staff',
    'admin.approve': 'Approve',
    'admin.reject': 'Reject',
    'admin.details': 'Details',
    'admin.verification_pending': 'Verification Pending',
    'landing.welcome': 'Welcome to Meliq Equb',
    'landing.hero.title': 'Equb Management',
    'landing.hero.title_modern': 'Modern',
    'landing.hero.title_way': 'Way',
    'landing.hero.subtitle': 'Meliq Equb combines traditional culture with modern technology, bringing transparency, security, and convenience.',
    'landing.hero.cta': 'Sign Up Now',
    'landing.hero.login': 'Login',
    'landing.join_cta': 'Join Ekub',
    'landing.video_cta': 'How it works',
    'landing.global_members': 'Global Members',
    'landing.life_title': 'Lead your life with modern Ekub',
    'landing.life_desc': 'Free from paper and traditional errors, technology-supported transparent and secure Ekub service.',
    'landing.trust_points.1': '100% Transparency',
    'landing.trust_points.2': 'Fast Payout',
    'landing.trust_points.3': 'Trusted Guarantee',
    'landing.about.title': 'What is Equb?',
    'landing.about.desc': 'Equb is a traditional Ethiopian savings and credit association. Members periodically contribute a fixed amount of money, which is then given to one member at a time on a rotating basis or by lot. Meliq Equb modernizes this system with technology to make it more transparent and reliable.',
    'feature.admin.title': 'Easy Management',
    'feature.admin.desc': 'Easily control Equb groups and members.',
    'feature.security.title': 'Secure Payments',
    'feature.security.desc': 'Track and verify payments in a modern way.',
    'feature.transparency.title': 'Transparency',
    'feature.transparency.desc': 'Track Equb activities transparently in real-time.',
    'feature.rewards.title': 'Member Rewards',
    'feature.rewards.desc': 'Provide special rewards and incetives for members.',
    'feature.reports.title': 'Reports',
    'feature.reports.desc': 'Monitor Equb activities with detailed reports.',
    'feature.fast.title': 'Fast Service',
    'feature.fast.desc': 'Execute Equb processes instantly.',
    'btn.save': 'Save',
    'btn.cancel': 'Cancel',
    'signin': 'Sign In',
    'signup': 'Sign Up',
    'phone': 'Phone Number',
    'password': 'Password',
    'full_name': 'Full Name',
    'country': 'Country',
    'region': 'Region',
    'zone': 'Zone',
    'woreda': 'Woreda',
    'kebele': 'Kebele',
    'google_access': 'Sign in with Google',
    'no_account': "Don't have an account?",
    'join_now': 'Join Now',
    'signup.personal': 'Personal Info',
    'signup.birthplace': 'Birthplace',
    'signup.address': 'Address',
    'signup.ekub_group': 'Equb & Group',
    'signup.kyc_photo': 'KYC & Photo',
    'signup.confirmation': 'Confirmation',
    'signup.identity_verification': 'Identity Verification',
    'signup.age': 'Age',
    'birth_country': 'Birth Country',
    'birth_region': 'Birth Region',
    'birth_zone': 'Birth Zone',
    'birth_woreda': 'Birth Woreda',
    'birth_kebele': 'Birth Kebele',
    'birth_date': 'Birth Date',
    'common.step': 'Step',
    'common.finish': 'Finish Registration',
    'signup.frequency': 'Frequency',
    'signup.members': 'Members',
    'signup.contribution': 'Contribution',
    'signup.slots': 'Slots',
    'signup.custom_amount': 'Custom Amount',
    'signup.national_id': 'National ID Number',
    'signup.face_scan': 'Face Scan',
    'signup.id_front': 'ID Front',
    'signup.id_back': 'ID Back',
    'signup.terms': 'I agree to the terms',
    'signup.success_title': 'Signup Successful!',
    'signup.member_code': 'Member Code',
    'signup.group_label': 'Group',
    'signup.registered_success_msg': 'Registration Successful!',
    'signup.success_desc': 'Your info has been sent for audit.',
    'signup.custom.option': 'Custom...',
    'signup.slot_unit': 'Slot(s)',
    'signup.spots_open': 'Spots open',
    'signup.registered_count': 'Registered',
    'signup.remaining_count': 'Remaining',
    'signup.take_photo': 'Take Photo',
    'signup.photo_uploaded': 'Photo Uploaded',
    'signup.upload_face_photo': 'Upload Face Photo',
    'signup.face_photo_security': 'Face photo required for security',
    'signup.registration_summary': 'Registration Summary',
    'signup.new_pool': 'New Pool',
    'signup.view_terms': 'View Terms and Conditions',
    'signup.finish_registration_note': 'After verifying your information, click "Finish Registration" below to complete your registration.',
    'signup.daily': 'Every 10 Days (Daily collected)',
    'signup.weekly': 'Weekly',
    'signup.monthly': 'Monthly',
    'signup.fivedays': 'Every 5 Days (Daily collected)',
    'signup.tendays': 'Every 10 Days (Daily collected)',
    'signup.daily_desc': 'Collected daily, draw happens every 10 days.',
    'signup.fivedays_desc': 'Collected daily, draw happens every 5 days.',
    'signup.tendays_desc': 'Collected daily, draw happens every 10 days.',
    'signup.weekly_desc': 'Contributions are weekly, and the draw happens weekly.',
    'signup.monthly_desc': 'Contributions are monthly, and the draw happens monthly.',
    'signup.cycle_note': 'This Equb type lasts {days} days per round',
    'signup.payout_calc': 'Your Payout = ({amount} ETB * {duration}) * {members} members',
    'signup.choose_group': 'Choose Group',
    'signup.error.full_name': 'Please enter your full name',
    'signup.error.phone': 'Please enter your phone number',
    'signup.error.password': 'Please enter your password',
    'signup.error.birth_country': 'Please enter birth country',
    'signup.error.birth_region': 'Please enter birth region',
    'signup.error.birth_zone': 'Please enter birth zone',
    'signup.error.registration_failed': 'Registration error occurred',
    'signup.error.phone_already_used': 'This phone number is already in use',
    'signup.alert.camera_denied': 'Camera access denied. Please grant permission.',
    'signup.alert.camera_not_ready': 'Camera not ready yet. Please wait.',
    'signup.error.birth_woreda': 'Please enter birth woreda',
    'signup.error.birth_kebele': 'Please enter birth kebele',
    'signup.error.birth_date': 'Please enter a valid birth date',
    'signup.error.age_limit': 'You must be at least 18 years old to register',
    'signup.error.address_country': 'Please enter country of residence',
    'signup.error.address_region': 'Please enter region of residence',
    'signup.error.address_zone': 'Please enter zone of residence',
    'signup.error.address_woreda': 'Please enter woreda of residence',
    'signup.error.address_kebele': 'Please enter kebele of residence',
    'signup.error.id_front': 'Please upload ID front photo',
    'signup.error.id_back': 'Please upload ID back photo',
    'signup.error.face_scan': 'Please upload face photo',
    'signup.error.national_id': 'Please enter national ID number',
    'signup.error.terms': 'Please agree to the terms and conditions',
    'signup.error.already_registered': 'This phone number is already registered. Please login or use another number.',
    'signup.error.frequency': 'Please select Equb frequency',
    'signup.error.member_limit': 'Please select member limit',
    'signup.error.amount': 'Please enter contribution amount',
    'signup.error.id_front_attach': 'Please attach ID front photo',
    'signup.error.id_back_attach': 'Please attach ID back photo',
    'signup.error.face_scan_perform': 'Please perform face scan',
    'signup.error.terms_agree': 'Please agree to the terms first',
    'common.year': 'Year',
    'common.year_unit': 'Years',
    'common.people': 'People',
    'common.day': 'Day',
    'calendar.gc': 'GC',
    'calendar.ec': 'EC',
    'calendar.year': 'Year',
    'calendar.month': 'Month',
    'calendar.day': 'Day',
    'calendar.gregorian': 'Gregorian',
    'calendar.ethiopian': 'Ethiopian',
    'signup.age_label': 'Age',
    'signup.payout_label': 'Expected Payout',
    'btn.continue': 'Continue',
    'signup.birthplace.region': 'Birth Region',
    'signup.birthplace.zone': 'Birth Zone',
    'signup.birthplace.woreda': 'Birth Woreda',
    'signup.birthplace.kebele': 'Birth Kebele',
    'signup.address.region': 'Region',
    'signup.address.zone': 'Zone',
    'signup.address.woreda': 'Woreda',
    'signup.address.kebele': 'Kebele',
    'signup.terms_desc': 'Ekub Rules and Regulations:\n1. Members must not delay during contributions. Any member failing to pay on time will be penalized according to the law.\n2. A winner must present three (3) guarantors before receiving the payout.\n3. Guarantors are required to provide Fayda ID and Business License.\n4. Winners must appear in person to fill out name forms and sign a "received" confirmation.\n5. Guarantors must also sign the guarantee document, specifying their name, profession, and address.\n6. Any member cannot exit the Ekub before completing their contributions.\n7. The admin has full authority to maintain the safety of the Ekub and suspend members who violate rules.',
    'dashboard.loading': 'Loading Information...',
    'dashboard.won_title': 'Congratulations!',
    'dashboard.won_subtitle': 'You are the winner of this round',
    'dashboard.guarantor_form': 'Guarantor Form',
    'dashboard.guarantor_label': 'Guarantor',
    'dashboard.guarantor_name': 'Full Name',
    'dashboard.guarantor_job': 'Job / Address',
    'dashboard.guarantor_confirm': 'I confirm I will sign in person',
    'dashboard.send_guarantors': 'Send Guarantor Info',
    'dashboard.pending_title': 'Registration Pending',
    'dashboard.pending_desc': 'Your information is being reviewed by the admin. You will gain full access once verified. Please wait patiently.',
    'dashboard.contribute_title': 'Send Contribution',
    'dashboard.contribute_desc': 'Please confirm the amount. Payment will reflect after admin verification.',
    'dashboard.receipt_label': 'Payment Receipt',
    'dashboard.receipt_upload': 'Select / Take Photo',
    'dashboard.submit_payment': 'Submit Payment',
    'dashboard.payment_sent_success': 'Payment sent! It will show up after admin verification.',
    'dashboard.payment_sent_error': 'Failed to send payment. Please try again.',
    'dashboard.next_draw': 'Next Draw',
    'dashboard.draw_soon': 'Coming Soon...',
    'dashboard.total_cycle': 'Total Cycle',
    'dashboard.summary': 'Registration Summary',
    'dashboard.rules.1.title': 'Contribution Procedure',
    'dashboard.rules.1.content': 'Members must not delay during contributions. Those who fail to pay on time will be penalized according to the law.',
    'dashboard.rules.2.title': 'Guaranty Obligation (for winners)',
    'dashboard.rules.2.content': 'A winner must provide three (3) guarantors before receiving the draw.',
    'dashboard.rules.3.title': 'Guarantor Evidence',
    'dashboard.rules.3.content': 'Guarantors must provide Fayda ID and Business License.',
    'dashboard.rules.4.title': 'Proof of Receipt',
    'dashboard.rules.4.content': 'The winner must appear in person to sign and confirm receipt.',
    'dashboard.rules.5.title': 'Guarantor Signature',
    'dashboard.rules.5.content': 'Guarantors must sign the guarantee document, stating their name, job, and address.',
    'dashboard.rules.6.title': 'General Provisions',
    'dashboard.rules.6.content': 'No member can leave the Equb without completing their contributions. The admin has full authority to maintain safety and suspend members who violate rules.',

    // Additional Admin/Common
    'admin.management': 'Management',
    'admin.operations': 'Operations',
    'admin.system': 'System',
    'chat.voice_message': 'Voice Message',
    'chat.all_members': 'All Members',
    'chat.admin': 'Admin',
    'chat.type_message': 'Type a message...',
    'status.pending': 'Pending',
    'status.active': 'Active',
    'status.rejected': 'Rejected',
    'status.verified': 'Verified',
    'status.verified_secure': 'Verified & Secure',
    'status.action_required': 'Action Required: Audit',
    'auth.exit_admin': 'Exit Admin',
    'auth.welcome_back': 'Welcome Back!',
    'auth.user_not_found': 'No user found with this phone number',
    'auth.verification_code_sms': 'Your verification code: {code}',
    'auth.error_try_again': 'An error occurred, please try again',
    'auth.invalid_code': 'Invalid verification code',
    'auth.password_min_length': 'Password must be at least 6 characters',
    'auth.password_changed': 'Your password has been changed! You can now log in.',
    'auth.password_change_failed': 'Failed to change password',
    'auth.enter_phone': 'Please enter your phone number',
    'auth.enter_password': 'Please enter your password',
    'auth.incorrect_admin_password': 'Incorrect admin password',
    'auth.admin_creation_failed': 'Admin creation failed: ',
    'auth.invalid_credentials': 'Invalid login credentials (phone or password)',
    'auth.admin_login_issue': 'Admin login issue: Please check your credentials.',
    'auth.google_login_failed': 'Google login failed',
    'auth.forgot_password_title': 'Reset Password',
    'auth.enter_phone_subtitle': 'Enter your phone number',
    'auth.sending': 'Sending...',
    'auth.send_code': 'Send Code',
    'auth.verify_code_title': 'Verify Code',
    'auth.verify_code_subtitle': 'Enter the 6-digit code.',
    'auth.verify_button': 'Verify',
    'auth.new_password_title': 'New Password',
    'auth.new_password_subtitle': 'Enter your new password',
    'auth.changing_password': 'Changing...',
    'auth.forgot_password': 'Forgot Password?',
    'auth.login_button': 'Login',
    'auth.loading_login': 'Logging in...',
    'auth.enter_phone_placeholder': 'e.g. 0912345678',
    'auth.enter_password_placeholder': 'Enter your password here',
    'auth.terms_service': 'Terms of Service',
    'auth.privacy_policy': 'Privacy Policy',
    'auth.secure_gateway': 'Secure Gateway',
    'auth.admin_detected': 'Admin Detected',
    'auth.registration_success': 'Registration successful',
    'auth.unique_code': 'Your Unique Member Code',
    'auth.enter_portal': 'Enter Meliq Portal',
    'receipt.id': 'Receipt ID',
    'receipt.verified': 'Verified',
    'receipt.id_status': 'ID Status',
    'receipt.active_license': 'Active License',
    'receipt.legal_req': 'Legal verification required before payment',
    'receipt.download_success': 'Receipt downloaded successfully',
    'receipt.download_error': 'Failed to download receipt',
    'payout.pending_ledger': 'Liability Ledger Empty',
    'payout.no_guarantors': 'No Guarantors Submitted',
    'payout.guarantor_assets': 'Guarantor Assets',
    'payout.mandatory_kyc': 'Mandatory KYC captured (3/3)',
    'payout.guarantor_unit': 'Guarantor Unit',
    'group.start': 'Start Group',
    'group.draw': 'Draw Winner',
    'group.no_members': 'Group has no members',
    'group.started': 'Group started successfully!',
    'group.winner_selected': 'Winner selected successfully!',
    'common.language': 'Language',
    'common.english': 'English',
    'common.amharic': 'አማርኛ',
    'common.units': 'Slots',
    'common.unit_value': 'Unit Value',
    'common.total_cycle': 'Total Cycle',
    
    // Admin Alerts & Operations
    'admin.user_approved': 'User approved successfully!',
    'admin.user_approval_failed': 'Approval failed',
    'admin.user_rejected': 'User rejected',
    'admin.user_rejection_failed': 'Rejection failed',
    'admin.user_delete_confirm': 'Are you sure you want to reject this user?',
    'admin.user_delete_permanent_confirm': 'Are you sure you want to delete this user permanently? This action cannot be undone.',
    'admin.user_deleted': 'User deleted',
    'admin.user_deletion_failed': 'Deletion failed',
    'admin.admin_added': 'New admin added successfully!',
    'admin.admin_add_failed': 'Failed to add admin',
    'admin.admin_permissions_updated': 'Admin permissions updated!',
    'admin.admin_update_failed': 'Update failed',
    'admin.required_fields': 'Please fill in all required fields correctly',
    'admin.phone_already_registered': 'This phone number is already registered',
    'admin.password_weak': 'The password is too weak',
    'admin.member_registration_success': 'New member registered successfully!',
    'admin.member_registration_failed': 'Failed to register member',
    'admin.user_info_updated': 'User information updated!',
    'admin.user_update_failed': 'Update failed',
    'admin.payment_approved': 'Payment approved!',
    'admin.payment_approval_failed': 'Failed to approve payment',
    'admin.payment_rejected': 'Payment rejected',
    'admin.payment_rejection_failed': 'Rejection failed',
    'admin.notification_sent': 'Notification sent',
    'admin.payment_registered_success': 'Payment registered successfully!',
    'admin.payment_registration_failed': 'Failed to register payment',
    'admin.pdf_generation_error': 'Failed to generate receipt',
    'admin.group_started': 'Group started successfully!',
    'admin.group_start_failed': 'Failed to start group',
    'admin.draw_winner_confirm': 'Are you sure you want to pick this winner?',
    'admin.draw_winner_error': 'Failed to draw winner',
    'admin.winner_notification_title': 'Congratulations!',
    'admin.winner_notification_message': 'You have been selected as the winner of this Equb round. Congratulations!',
    'time.just_now': 'Just now',
    'time.hours_ago': '{hours}h ago',
    'time.days_ago': '{days}d ago',
    'time.unknown': 'Unknown',
    
    // UI Sections & Headers
    'admin.kyc_verification_hub': 'KYC Verification Hub',
    'admin.identity_audit_subtitle': 'Global Identity Audit & Access Control',
    'admin.search_records_placeholder': 'Search master records...',
    'admin.regional_intake_dist': 'Regional Intake Distribution',
    'admin.pending_audits_empty': 'All Clear! No Pending Audits',
    'admin.kyc_requirements_met': 'Everything is captured. Great job!',
    'admin.security_clearance': 'Security Clearance',
    'admin.audit_assets': 'Audit Assets',
    'admin.verify_identity': 'Verify Identity',
    'admin.master_directory_intelligence': 'Members Directory',
    'admin.verified_directory': 'Verified Directory',
    'admin.active_status': 'Active Status',
    'admin.regional_clusters': 'Regional Clusters',
    'admin.system_health': 'System Health',
    'admin.group_ecosystem': 'Group Ecosystem',
    'admin.group_monitor_subtitle': 'Monitor group cycles, members, and draws',
    'admin.total_groups': 'Total Groups',
    'admin.live': 'Live',
    'admin.total_winners': 'Total Winners',
    'admin.total_value': 'Total Value',
    'admin.legal_guarantors': 'Legal Guarantors',
    'admin.trust_verification_subtitle': 'Trust Verification & Liability Audit',
    'admin.under_review': 'Under Review',
    'admin.legal_compliance_policy': 'Legal Compliance Policy',
    'admin.identity_verification': 'Identity Verification',
    'admin.reviewing_profile': 'Reviewing profile',
    'admin.liveness_check': 'Liveness Check',
    'admin.document_verification': 'Document Verification',
    'admin.reject_request': 'Reject Request',
    'admin.confirm_approve_member': 'Confirm & Approve Member',
    'admin.revenue_insight': 'Revenue Insight',
    'admin.recent_logs': 'Recent Logs',
    'admin.new_signups': 'New Signups',
    'admin.last_6_months': 'Last 6 Months',
    'admin.user_growth': 'User Growth',
    'admin.add_new_member': 'Add New Member',
    'admin.members_directory': 'Members Directory',
    'admin.groups_directory_desc': 'Manage group activities and members',
    'admin.draws_desc': 'Manage and track draw process',
    'admin.guarantors_desc': 'Manage and track guarantor information',
    'admin.admins_desc': 'Super admin control panel',
    'admin.professional_profile': 'Employment',
    'admin.broadcast': 'All Members',
    'admin.broadcast_subtitle': 'Global Broadcast',
    'admin.group_channel_subtitle': 'Group Channel',
    'admin.direct_message_subtitle': 'Direct Message',
    'admin.no_messages_yet': 'No Messages Yet',
    'admin.type_message_placeholder': 'Type a message...',
    'admin.edit_message_placeholder': 'Edit message...',
    'admin.group_chats': 'Groups',
    'admin.private_chats': 'Members',
    'admin.paid': 'Paid',
    'admin.addis_ababa': 'Addis Ababa',
    'admin.oromia': 'Oromia',
    'admin.amhara': 'Amhara',
    'admin.tigray': 'Tigray',
    'admin.sidama': 'Sidama',
    'admin.somali': 'Somali',
    'admin.all_regions': 'All Regions',
    'admin.recorded': 'Recorded',
    'admin.phone_registered': 'This phone number is already registered. Please use another number.',
    'admin.weak_password': 'The password is too weak. It should be at least 6 digits.',
    'admin.user_registered_success': 'New member registered successfully. The member can now login with their phone number and the chosen password!',
    'admin.admin_label': 'Admin',
    'admin.photo_id': 'Photo ID',
    'admin.full_bio': 'Full Bio',
    'admin.documents': 'Documents',
    'admin.confidence': 'Confidence',
    'admin.user_updated': 'User information updated!',
    'admin.payment_approve_failed': 'Failed to approve payment',
    'admin.payment_reject_confirm': 'Are you sure you want to reject this payment?',
    'admin.payment_reject_failed': 'Rejection failed',
    'admin.language_label': 'Language',
    'admin.view_grid': 'Grid',
    'admin.view_list': 'List View',
    'admin.audit_required': 'Action Required: Audit',
    'admin.identity_staking': 'Mandatory Identity Stacking (3/3 Captured)',
    'admin.pay': 'Pay',
    'admin.no_pending_payments': 'No pending payments detected',
    'admin.no_payment_history': 'No payment history available',
    'admin.pending_upload': 'PENDING_UPLOAD',
    'admin.send_notification': 'Send Notification',
    'admin.subject': 'Subject',
    'admin.message': 'Message',
    'admin.send': 'Send',
    'admin.winner_selected_msg': 'Winner {name} has been selected!',
    'admin.draw_failed': 'Failed to draw winner',
    'admin.no_members_in_group': 'Group has no members',
    'admin.winner_confirm_msg': 'Are you sure you want to select {name} as the winner?',
    'admin.receipt': 'Receipt',
    'admin.super_access': 'Super Access',
    'admin.administrator': 'Administrator',
    'admin.profession': 'Profession',
    'admin.bank_name': 'Bank Name',
    'admin.bank_account': 'Bank Account',
    'admin.security_note_title': 'Your Security is Protected',
    'admin.security_note_desc': 'Members registered here can log in directly using their phone number and chosen password. Their personal information is kept confidential.',
    'admin.add_member_button': 'Register Member',
    'admin.stat_awaiting_audit': 'Identities awaiting audit',
    'admin.stat_throughput': 'Throughput velocity',
    'admin.stat_confidence': 'Confidence interval',
    'admin.stat_directory_size': 'Verified directory size',
    'admin.pot_fund': 'Pot Fund',
    'admin.membership_fill': 'Membership Fill',
    'admin.recent_contributors': 'Recent Contributors',
    'admin.no_members_yet': 'No members joined yet',
    'admin.contribution_slots': 'Contribution Slots',
    'admin.legal_framework': 'Legal Framework',
    'admin.legal_framework_subtitle': 'Meliq Ekub Operating Rules and Regulations',
    'admin.integrity_notice_title': 'System Integrity Notice',
    'admin.integrity_notice_desc': 'These guidelines are applicable to all members and are designed to ensure the survival of the Ekub. In case of any dispute, the admin decision will be final.',
    'admin.registration_period': 'Registration Period',
    'rules.title_1': 'Contribution Procedure',
    'rules.content_1': 'Members must not be late during contributions. Any member who does not pay on time will be penalized according to the law.',
    'rules.title_2': 'Guaranty Obligation (for winners)',
    'rules.content_2': 'A member who wins the draw must present three (3) guarantors before receiving the funds.',
    'rules.title_3': 'Guarantors Evidence',
    'rules.content_3': 'Guarantors are required to provide Fayda ID and Business License.',
    'rules.title_4': 'Confirmation of Receipt',
    'rules.content_4': 'The winning member must appear in person to fill out the form and sign a confirmation of receipt.',
    'rules.title_5': 'Guarantors Signature',
    'rules.content_5': 'Guarantors must also sign the guaranty document, stating their name, profession, and address.',
    'rules.title_6': 'General Provisions',
    'rules.content_6': 'No member can leave the Ekub without completing their contribution. The admin has full power to maintain the security of the Ekub and suspend members who violate the rules.',
    'dashboard.notifications': 'Notifications',
    'dashboard.recent_notifications': 'Recent Notifications',
    'dashboard.no_notifications': 'No transmission detected',
    'dashboard.core_support': 'Core Support',
    'dashboard.support_desc': 'If you have any questions about the Ekub or any operational matters, you can contact our support team at any time.',
    'dashboard.contact_support': 'Contact Collective Support',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('am');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

